baseurl = "https://visualstudio.gitclub.cn/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "GitLab  Extension for Visual Studio"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Create value faster with the only integrated product for the whole software development lifecycle."
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 1, 2017"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "maikebing"
  email = "100860505@qq.com"
  facebook = "maikebing"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab = "maikebing"
  github = "maikebing"
  twitter = "maikebing"
  #reddit = "username"
  #linkedin = "username"
 # xing = "username"
  stackoverflow = "users/7779862/mysticboy"
  #snapchat = "username"
 # instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"


[[menu.main]]
    name = "Overview"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "Links"
    name = "Links"
    weight = 2

[[menu.main]]
    parent = "Links"
    name = "BUG And Issues"
    url = "https://gitlab.com/maikebing/GitLab.VisualStudio/issues"
    weight = 1

[[menu.main]]
    parent = "Links"
    name = "Visual Studio | Marketplace"
    url = "https://marketplace.visualstudio.com/items?itemName=MysticBoy.GitLabExtensionforVisualStudio"
    weight = 2
[[menu.main]]
    parent = "Links"
    name = "About author"
    url = "https://github.com/maikebing"
    weight = 3
 
[[menu.main]]
    name = "release-notes"
    url = "release-notes"
    weight = 3
